name: Build
on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v2
        with:
          path: node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('**/yarn.lock') }}
      - run: yarn install --frozen-lockfile
      - run: yarn validate

  test-coverage:
    needs: test
    name: test-coverage
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-node@master
        with:
          node-version: 16
      - uses: actions/cache@v1
        with:
          path: node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('**/yarn.lock') }}
      - run: yarn install --frozen-lockfile
      - uses: paambaati/codeclimate-action@v2.7.2
        env:
          CC_TEST_REPORTER_ID: ${{ secrets.CC_TEST_REPORTER_ID }}
        with:
          coverageCommand: yarn ci:test:coverage
          debug: true

  release:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Semantic Release
        uses: cycjimmy/semantic-release-action@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}

  publish:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: actions/cache@v2
        with:
          path: node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('**/yarn.lock') }}
      - run: yarn install --frozen-lockfile
      - run: yarn build
      - id: dotenv
        uses: falti/dotenv-action@v0.2.5
      - name: Publish docker image
        uses: filmcalendar/build-agents-action@main
        with:
          fc-country: ${{ steps.dotenv.outputs.FC_COUNTRY }}
          docker-registry-password: ${{ secrets.GH_TOKEN }}
      - uses: actions/delete-package-versions@v1
        with:
          package-name: fc-agents-${{ steps.dotenv.outputs.FC_COUNTRY }}
