name: Publish
on:
  workflow_dispatch:
  push:
    tags:
      - v*

jobs:
  publish:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: actions/cache@v2
        with:
          path: node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('**/yarn.lock') }}
      - run: yarn install --frozen-lockfile
      - run: yarn build
      - name: Publish docker image
        uses: filmcalendar/build-agents-action@main
        with:
          country: uk
          dockerRegistryPassword: ${{ secrets.GH_TOKEN }}
