name: Publish
on:
  workflow_dispatch:
  release:
    types:
      - created

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - run: yarn install --frozen-lockfile
      - run: yarn build
      - name: Publish docker image
        uses: filmcalendar/build-agents-action@main
        with:
          country: uk
